config/routes.rb
CcDev1::Application.routes.draw do

  match "/single_art" => "home#single_article", :as => :single_art
  match "/user_reg" => "home#user_reg", :as => :user_reg
  match "/user_prof" => "home#user_prof", :as => :user_prof
  match "/admin/example_form" => "mtest#example_form", :as => :example_form

  match "/admin" => "admin#index", :as => :admin
  match "/admin/login" => "admin#login", :as => :admin_login
  match "/admin/enter" => "admin#enter", :as => :admin_enter
  match "/admin/logout" => "admin#logout", :as => :admin_logout

  match "/szukaj/:keyword" => "home#search", :as => :search_word
  match "/szukaj" => "home#search", :as => :search

  devise_for  :users, 
              :path => 'uzytkownicy', 
              :path_names => { :sign_in => "logowanie", :sign_out => "wyloguj" }, 
              :controllers => { :registrations => "registrations" } do
  end

  resources :users, :path => 'users'
  resources :places
  resources :posts
  resources :preferences

  match "/nastepne-posty" => "home#load_more_posts", :as => :load_more_posts
  match "/post/:id" => "front_posts#show", :as => :single_post

  match "/miejsca" => "front_places#index", :as => :front_places
  match "/miejsca/:category" => "front_places#index"
  match "/miejsca/:category/strona_:page" => "front_places#index"
  match "/pokaz-miejsca" => "front_places#add_places_to_map", :as => :add_places_to_map
  match "/miejsce/:id" => "front_places#show", :as => :single_place  

  match "/kalendarz" => "home#calendar", :as => :calendar
  match "/kalendarz/:year/:month/:week" => "home#calendar", :as => :calendar_date
  match "/kontakt" => "home#contact", :as => :contact
  match "/o_nas" => "home#about", :as => :about
  match "/regulamin" => "home#terms", :as => :terms

  match "/:category" => "home#index", :as => :category

  root :to => 'home#index'

end

app/views/shared/_footer-link.html.erb
<footer>
  <ul class="foot part1">
    <p class="foot-title">Sitemap</p>
      <li class="orange-foot"><%= link_to "Rozrywka", category_url('rozrywka') %></li>
      <li class="green-foot"><%= link_to "Kultura", category_url('kultura') %></li>
      <li class="blue-foot"><%= link_to "Studia", category_url('studia') %></li>
      <li class="pink-foot"><%= link_to "Lifestyle", category_url('lifestyle') %></li>
      <li class="yellow-foot"><%= link_to "Miejsca", front_places_url %></li>
      <li class="white-foot"><%= link_to "Kalendarz", calendar_path %></li>
  </ul>
  
  <ul class="foot part2">
    <p class="foot-title">Top tagi</p>
    <% @tags = Post.tag_counts_on(:tags).order("count DESC").limit(6) %>  
    <% @tags.each do |t| %>
      <li class="white-foot"><%= link_to t.name, search_word_url(:keyword => t.name) %></li>  
    <% end %>
  </ul>

  <ul class="foot part3">
    <p class="foot-title">Top newsy</p>
    <% @news = Post.order("id DESC").limit(6) %>
    <% @news.each do |p| %>
      <li class="<%= cat_col(p.category_id) %>-foot"><%= link_to p.title, single_post_url(p) %></li>
    <% end %>
  </ul>

  <ul class="foot part4">
    <p class="foot-title">CollegeCity</p>
    <li><%= link_to "O nas", about_path %></li>
    <li><%= link_to "Zasady i regulamin", terms_path %></li>
    <li><%= link_to "Kontakt", contact_url %></li>
    <p class="foot-title">Lets socialize</p>
    <a href="https://www.facebook.com/CollegeCity" target="_blank" class="ft-socials fb-btn"></a>
  </ul>
</footer>

app/views/shared/_post_box.html.erb
<% @posts.each do |p| %>
  <% b_size = box_size(p) %>
  <div class="mason w<%= b_size %>00">
    <div class="w<%= b_size %>">
      <a href="<%= single_post_url(p) %>">
        <span class="fade-hover"></span>
        <span class="<%= cat_col(p.category_id) %>-ico ico"></span>
        <%= image_tag p.main_photo_link("list") %>
        <p class="<%= cat_col(p.category_id) %> m-title"><%= p.title %></p>
      </a>
    </div>
    <p class="snippet">
      <%= p.lead.truncate(120) %>
    </p>
  </div>
<% end %>