config/routes.rb
CcDev1::Application.routes.draw do

  match "/single_art" => "home#single_article", :as => :single_art
  match "/user_reg" => "home#user_reg", :as => :user_reg
  match "/user_prof" => "home#user_prof", :as => :user_prof
  match "/admin/example_form" => "mtest#example_form", :as => :example_form

  match "/admin" => "admin#index", :as => :admin
  match "/admin/login" => "admin#login", :as => :admin_login
  match "/admin/enter" => "admin#enter", :as => :admin_enter
  match "/admin/logout" => "admin#logout", :as => :admin_logout

  match "/szukaj/:keyword" => "home#search", :as => :search_word
  match "/szukaj" => "home#search", :as => :search

  devise_for  :users, 
              :path => 'uzytkownicy', 
              :path_names => { :sign_in => "logowanie", :sign_out => "wyloguj" }, 
              :controllers => { :registrations => "registrations" } do
  end

  resources :users, :path => 'users'
  resources :places
  resources :posts
  resources :preferences

  match "/nastepne-posty" => "home#load_more_posts", :as => :load_more_posts
  match "/post/:id" => "front_posts#show", :as => :single_post

  match "/miejsca" => "front_places#index", :as => :front_places
  match "/miejsca/:category" => "front_places#index"
  match "/miejsca/:category/strona_:page" => "front_places#index"
  match "/pokaz-miejsca" => "front_places#add_places_to_map", :as => :add_places_to_map
  match "/miejsce/:id" => "front_places#show", :as => :single_place  

  match "/kalendarz" => "home#calendar", :as => :calendar
  match "/kalendarz/:year/:month/:week" => "home#calendar", :as => :calendar_date
  match "/kontakt" => "home#contact", :as => :contact
  match "/o_nas" => "home#about", :as => :about
  match "/regulamin" => "home#terms", :as => :terms

  match "/:category" => "home#index", :as => :category

  root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include ApplicationHelper


  def search
    sort_order = case params[:sort]
    when 'name_asc' then 'name asc'
    when 'name_desc' then 'name desc'
    when 'created_asc' then 'created_at asc'
    when 'created_desc' then 'created_at desc'
    else 'created_at desc'
    end

    @posts = Post.order(sort_order)
    if params[:keyword].present?
      params[:keyword] = params[:keyword].truncate(50)
      keywords = params[:keyword].gsub(/[=,;\"\'%\\#\{\\(\)}\$`]/, '').split(' ')
      short_keywords = keywords.select{|k| k.size <= 2}
      long_keywords = keywords.select{|k| k.size > 2}
      @short_posts = ( short_keywords.present? ? @posts.tagged_with(short_keywords, :any => true) : [] )
      @long_posts = ( long_keywords.present? ? @posts.tagged_with(long_keywords, :wild => true, :any => true) : [] )
      @posts = @short_posts + @long_posts
    end

    @posts = Kaminari.paginate_array( @posts.uniq ).page(params[:page]).per(24)
  end


  def load_more_posts
    @page = params[:page]
    @per_page = 30
    if params[:category].present?
      @posts = Post.normal.active.where("category_id = #{cat_id_from_param(params[:category])}").order("id DESC").paginate(:page => @page, :per_page => @per_page)
    else
      @posts = Post.active.normal.order("id DESC").paginate(:page => @page, :per_page => @per_page)
    end

    respond_to do |format|
      format.js
    end
  end


  def index
    @page = 1
    @per_page = 30
    if params[:category].present?
      @promoted_posts = Post.active.promoted.where("category_id = #{cat_id_from_param(params[:category])}").limit(10)
      @posts = Post.normal.active.where("category_id = #{cat_id_from_param(params[:category])}").order("id DESC").paginate(:page => @page, :per_page => @per_page)
    else
      @promoted_posts = Post.active.promoted.limit(10)
      @posts = Post.active.normal.order("id DESC").paginate(:page => @page, :per_page => @per_page)
    end
  end


  def calendar
    @years = Post.find_by_sql("SELECT DISTINCT(YEAR(event_start)) AS year FROM posts WHERE is_event = true").collect{|p| p.year}
    params[:year] = year = (params[:year] || Time.now.strftime('%Y'))
    params[:month] = month = (params[:month] || Time.now.strftime('%m'))
    day_cond, params[:week] = prepare_days_condition(params[:week])

    posts = Post.active.where("is_event = true AND YEAR(event_start) = #{year} AND MONTH(event_start) = #{month} #{day_cond}").to_a
    @grouped_posts = posts.group_by{|p| p.event_start.to_date}
  end


  def prepare_days_condition(week=nil)
    if week.present?
      case week.to_i
      when 1 then
        s = 1
        e = 8
      when 2 then
        s = 9
        e = 16
      when 3 then
        s = 17
        e = 24
      when 4 then
        s = 25
        e = 31
      end
    else
      d = Time.now.strftime('%d').to_i
      if (1..8).to_a.include?(d)
        s = 1
        e = 8
        week = 1
      elsif (9..16).to_a.include?(d)
        s = 9
        e = 16
        week = 2
      elsif (17..24).to_a.include?(d)
        s = 17
        e = 24
        week = 3
      elsif (26..31).to_a.include?(d)
        s = 25
        e = 31
        week = 4
      end
    end
    day_cond = "AND DAY(event_start) >= #{s} AND DAY(event_start) <= #{e}"
    [day_cond, week]
  end

  def terms
    
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<div class="user-profile">
	<h1 class="general">O nas</h1>
	<br>
	<p>
		Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam imperdiet eros eget nisl molestie pretium. Proin ut tortor sit amet lacus pulvinar hendrerit et nec sapien. Praesent eu odio nisl. Aenean iaculis volutpat adipiscing. Sed a tempus metus. Vestibulum gravida tempus imperdiet. Quisque quis pellentesque leo. Maecenas posuere nulla at eros vestibulum blandit. Vivamus nec metus at odio malesuada interdum ac in metus. Duis ultrices fringilla tortor eget rhoncus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse scelerisque nulla scelerisque sapien cursus nec rutrum lorem posuere. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean ante dolor, ultricies in bibendum sed, viverra quis tellus. Vivamus quis sapien sodales justo luctus lobortis vitae sit amet urna. Quisque sit amet lacinia lectus.</p>
	<br>
	<p>
		Proin eu nulla ac odio laoreet blandit. Duis tristique condimentum mauris, ac mollis metus dapibus sed. Phasellus congue, urna non sollicitudin consequat, lorem nibh dapibus mi, vitae dictum lectus urna id leo. Nam id dui lorem. Praesent eu ante at leo commodo varius. Curabitur nec turpis quis neque gravida iaculis eu eget est. Donec luctus tellus eu dolor imperdiet venenatis. Ut vitae nibh id sapien laoreet laoreet. Morbi tellus orci, rhoncus id elementum viverra, dignissim non orci. Pellentesque sed erat id urna luctus sodales. Nunc vel neque ac lectus vehicula hendrerit. Nunc egestas tristique euismod. Cras venenatis volutpat egestas. Aenean gravida ultricies ullamcorper. Morbi non porttitor lacus.
	</p>
	<br>
	<p>
		Praesent a nulla arcu. Etiam quis mauris id diam consectetur iaculis. Nam sed ligula metus. Integer est dui, sodales ac ultrices a, tincidunt sed neque. Aenean accumsan felis at dui eleifend eget molestie tellus venenatis. Maecenas ac tortor erat. Curabitur posuere neque id tellus lobortis interdum. Proin non orci quis nibh vestibulum malesuada. Suspendisse convallis tincidunt dictum. Nunc ut arcu eget mi placerat tempus quis quis turpis.
	</p>
	<br>
	<p>
		Aliquam ullamcorper, tortor vel pellentesque malesuada, odio mi rhoncus nisi, non scelerisque leo orci at arcu. Nunc id sem id justo ullamcorper sodales. Aliquam vulputate libero faucibus lacus cursus a pulvinar est feugiat. Nam blandit neque vitae est sodales at sagittis nulla rhoncus. Duis fringilla mauris turpis, vel dignissim sapien. Curabitur placerat velit et nisi tincidunt in tristique urna iaculis. Quisque lacus nulla, iaculis vel lobortis vitae, varius ut justo. Suspendisse et dolor id massa dapibus ornare.
	</p>
	<br>
	<p>
		Morbi vitae elit neque. Phasellus diam diam, vestibulum at imperdiet vitae, sagittis a risus. In at erat erat. Sed velit nisi, scelerisque quis tristique vitae, bibendum eget massa. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In sodales consequat diam. Sed scelerisque, magna sit amet malesuada consequat, massa lacus sollicitudin nisi, quis pretium lorem sapien in mi.
	</p>
	<br>
</div>

app/views/home/calendar.html.erb
<div class="cal-header">
	<div class="cal-archives">Pokaż archiwum:
		<%= select_tag :year, options_for_select(@years, params[:year]), :class => "cat_year" %>
		<%= select_tag :month, options_for_select(MONTHS_TO_SELECT, params[:month]), :class => "cat_month" %>
		<%= select_tag :week, options_for_select(WEEK_TO_SELECT, params[:week]), :class => "cat_week" %>
		<%= link_to "Ustaw", "#", :class => "cal-btn change_cal_date_link" %>

		<script type="text/javascript">
			$('.change_cal_date_link').click(function() {
				var year = $('.cat_year').val();
				var month = $('.cat_month').val();
				var week = $('.cat_week').val();
				document.location.href='<%= calendar_url %>/'+year+'/'+month+'/'+week;
				return false;
			});
		</script>
	</div>

	<h1 class="cal-title">Kalendarz Wydarzeń</h1>
</div>

<div class="calendar-holder">
	<%= link_to "Poprzednie", calendar_date_url( previous_calendar_params(params[:year], params[:month], params[:week]) ) %>

	<% if @grouped_posts.present? %>
		<% @grouped_posts.each do |posts| %>
			<div class="cal-head-date"><%= posts[0].strftime("%d %B") %></div>
			<table cellpadding="0" cellspacing="0" class="main-cal-table">
				<% posts[1].each do |p| %>
					<tr class="row-<%= cat_col(p.category_id) %>">
						<td class="ch-time"><%= p.event_start.strftime("%H:%M") %></td>
						<td class="ch-title"><%= link_to p.title, single_post_url(p), :class => "cal-news ch-#{cat_col(p.category_id)}" %></td>
						<% place = p.place %>
						<td class="ch-street">
							<% if place.present? %>
								<%= "#{place.street} #{place.street_no}, #{place.city}" %>
							<% end %>
						</td>
						
						<td class="ch-more"><%= link_to "Zobacz więcej »", single_post_url(p), :class => "chlink-#{cat_col(p.category_id)}" %></td>
					</tr>
				<% end %>
			</table>
		<% end %>
	<% else %>
		W tym przedziale czasu nie odbywają się żadne wydarzenia. Wybierz inny przedział.
	<% end %>

	<%= link_to "Następne", calendar_date_url( next_calendar_params(params[:year], params[:month], params[:week]) ) %>
</div>

app/views/home/contact.html.erb
<div class="user-profile">
	<h1 class="general">Kontakt</h1>
</div>

app/views/home/index.html.erb
<div>
	<div id="slides">
    <div class="slides_container">
      <% @promoted_posts.each do |pp| %>
      <div>	          
          <div class="slider-content">
          <a href="<%= single_post_url(pp) %>">
            <span class="slide-cut"></span>
            <%= image_tag pp.main_photo_link("main"), :alt => 'photo' %>
            <p class="slide-article <%= cat_col(pp.category_id) %>">
              <span class="slide-caption <%= cat_col(pp.category_id) %>"><%= pp.title %></span>
              <span class="clear slide-lead"><%= pp.lead %></span>
            </p>
          </a> 
          </div>
      </div>
      <% end %>
    </div>
  </div>
</div>


<script>
  $(function(){
      $("#slides").slides({
        effect: 'fade',
        paginationClass: 'slide-page',
        play: 5000
      });
  });
</script>


<div class="mason-holder post_box">
  <%= render 'shared/post_box' %>
</div>


<script type="text/javascript" src="http://www.beyondcoding.com/demos/endless-scroll/js/jquery.endless-scroll-1.3.js"></script>
<script type="text/javascript" charset="utf-8">
  function loadMore(pageNr) {
    if (enable_loading == true) {
      enable_loading = false;
      $.ajax({
        format: 'JS',
        type: "POST",
        url: '<%= load_more_posts_url %>',
        data: { page: pageNr,
                category: "<%= params[:category] %>" }
      }).done(function() {
        $('.places_loading').hide();      
      });
    }
  }

  var enable_loading = true;
  var currentPage = 2;
  $(document).ready(function(){
    $(document).endlessScroll({
      bottomPixels: 1000,
      fireDelay: 10,
      callback: function(p){
        loadMore(currentPage);
      }
    });
  });
</script>

app/views/home/search.html.erb
<% @posts.each do |p| %>
  <%= link_to single_post_url(p) do %>
    <%= p.id %> - <%= p.title %> - <%= p.tags.collect{|t| t.name} %><br/>
  <% end %>
<% end %>

app/views/home/single_article.html.erb
<div class="main-article-holder">

  <div class="first-article-image">
    <span class="article-triangle"></span>
    <img src="http://fc09.deviantart.net/fs70/i/2012/257/e/d/nir_universe_005_by_albino_z-d5ephso.jpg" width="530px" />
  </div>

  <div class="article-header orange-f">
    <h1 class="for-articles orange"><span>Post title goes over here - and this is awesome stuff.</span></h1>
  </div>
  <div class="clear first-caption orange">Caption for the main picture</div>
  <div class="clear additional-article-images">
    <img src="http://fc04.deviantart.net/fs70/f/2012/322/6/2/vw_rigshot_by_giifoto-d5lczg1.jpg" />
  </div>
  <div class="clear first-caption orange">Caption for the main picture</div>

<div class="article-content">
  <div class="article-date">23 Listopad 2012</div>
  <p class="article-lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed pretium dui quis ante convallis nec fringilla leo suscipit. Etiam et neque urna. Nulla mollis iaculis tempor. Aliquam tincidunt blandit nibh non cursus. Donec risus ligula, adipiscing non iaculis et, placerat sed velit. Proin ornare blandit tellus at dapibus. Curabitur felis urna, placerat feugiat interdum</p>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed pretium dui quis ante convallis nec fringilla leo suscipit. Etiam et neque urna. Nulla mollis iaculis tempor. Aliquam tincidunt blandit nibh non cursus. Donec risus ligula, adipiscing non iaculis et, placerat sed velit. Proin ornare blandit tellus at dapibus. Curabitur felis urna, placerat feugiat interdum</p>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed pretium dui quis ante convallis nec fringilla leo suscipit. Etiam et neque urna. Nulla mollis iaculis tempor. Aliquam tincidunt blandit nibh non cursus. Donec risus ligula, adipiscing non iaculis et, placerat sed velit. Proin ornare blandit tellus at dapibus. Curabitur felis urna, placerat feugiat interdum</p>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed pretium dui quis ante convallis nec fringilla leo suscipit. Etiam et neque urna. Nulla mollis iaculis tempor. Aliquam tincidunt blandit nibh non cursus. Donec risus ligula, adipiscing non iaculis et, placerat sed velit. Proin ornare blandit tellus at dapibus. Curabitur felis urna, placerat feugiat interdum</p>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed pretium dui quis ante convallis nec fringilla leo suscipit. Etiam et neque urna. Nulla mollis iaculis tempor. Aliquam tincidunt blandit nibh non cursus. Donec risus ligula, adipiscing non iaculis et, placerat sed velit. Proin ornare blandit tellus at dapibus. Curabitur felis urna, placerat feugiat interdum</p>
 
  
  <div class="article-socials">[article socials]</div>
  
  <div class="article-location">
    <h4 class="yellow">Dane miejsca</h4>
    <h2><%= link_to "Teatr Slowackiego", "" %></h2>
    <p class="location-snippet">
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed pretium dui quis ante convallis nec fringilla leo suscipit. Etiam et neque urna. Nulla mollis iaculis tempor. Aliquam tincidunt blandit nibh non cursus. Donec risus ligula, adipiscing non iaculis et, placerat sed velit. Proin ornare blandit tellus at dapibus. Curabitur felis urna
    </p>
    <table width="550px" cellspacing="0" cellpadding="0">
      <tr>
        <td width="40%" class="location-detail">Adres:</td>
        <td width="60%" class="location-info">ul. Krakowska 13A</td>
      </tr>
      <tr>
        <td width="40%" class="location-detail">Telefon:</td>
        <td width="60%" class="location-info">12 232 12 34</td>
      </tr>
      <tr>
        <td width="40%" class="location-detail">Strona www:</td>
        <td width="60%" class="location-info">www.tearslowacki.pl</td>
      </tr>
      <tr>
        <td width="40%" class="location-detail">Godziny otwarcia:</td>
        <td width="60%" class="location-info">
          pon - pt: 8.00 - 20.00<br>
          sobota: 8.00 - 22.00<br>
          niedziela: nieczynne
        </td>
      </tr>
      <tr>
        <td width="40%" class="location-detail">Cennik:</td>
        <td width="60%" class="location-info">20 zl</td>
      </tr>
      <tr>
        <td width="40%" class="location-detail"></td>
        <td width="60%" class="location-info"><%= link_to "Zobacz na mapie", "" %></td>
      </tr>
    </table>
  </div>
</div>
  <div class="clearspace"></div>
  
  
  <div class="orange more-from-us">CollegeCity Poleca!</div>
  <% 4.times do %>		  
  <div class="mason w200">
    <div class="w2">
      <a href="/single_art">
      <span class="fade-hover"></span>
      <span class="blue-ico ico"></span>
        <img src="https://fbcdn-sphotos-f-a.akamaihd.net/hphotos-ak-ash4/487412_531660170183336_643351316_n.jpg" alt="image" />
        <p class="blue m-title">Magical worlds now in theaters</p>
      </a>
    </div>
    <p class="snippet">
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed pretium dui quis ante convallis nec fringilla leo suscipit. Etiam et neque urna. Nulla mollis
    </p>
  </div>
  <% end %>
  <div class="clearspace"></div>
 
</div>

app/views/home/terms.html.erb
<div class="user-profile">
	<h1 class="general">Regulamin</h1>
	<br>
	<p>
		Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam imperdiet eros eget nisl molestie pretium. Proin ut tortor sit amet lacus pulvinar hendrerit et nec sapien. Praesent eu odio nisl. Aenean iaculis volutpat adipiscing. Sed a tempus metus. Vestibulum gravida tempus imperdiet. Quisque quis pellentesque leo. Maecenas posuere nulla at eros vestibulum blandit. Vivamus nec metus at odio malesuada interdum ac in metus. Duis ultrices fringilla tortor eget rhoncus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse scelerisque nulla scelerisque sapien cursus nec rutrum lorem posuere. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean ante dolor, ultricies in bibendum sed, viverra quis tellus. Vivamus quis sapien sodales justo luctus lobortis vitae sit amet urna. Quisque sit amet lacinia lectus.</p>
	<br>
	<p>
		Proin eu nulla ac odio laoreet blandit. Duis tristique condimentum mauris, ac mollis metus dapibus sed. Phasellus congue, urna non sollicitudin consequat, lorem nibh dapibus mi, vitae dictum lectus urna id leo. Nam id dui lorem. Praesent eu ante at leo commodo varius. Curabitur nec turpis quis neque gravida iaculis eu eget est. Donec luctus tellus eu dolor imperdiet venenatis. Ut vitae nibh id sapien laoreet laoreet. Morbi tellus orci, rhoncus id elementum viverra, dignissim non orci. Pellentesque sed erat id urna luctus sodales. Nunc vel neque ac lectus vehicula hendrerit. Nunc egestas tristique euismod. Cras venenatis volutpat egestas. Aenean gravida ultricies ullamcorper. Morbi non porttitor lacus.
	</p>
	<br>
	<p>
		Praesent a nulla arcu. Etiam quis mauris id diam consectetur iaculis. Nam sed ligula metus. Integer est dui, sodales ac ultrices a, tincidunt sed neque. Aenean accumsan felis at dui eleifend eget molestie tellus venenatis. Maecenas ac tortor erat. Curabitur posuere neque id tellus lobortis interdum. Proin non orci quis nibh vestibulum malesuada. Suspendisse convallis tincidunt dictum. Nunc ut arcu eget mi placerat tempus quis quis turpis.
	</p>
	<br>
	<p>
		Aliquam ullamcorper, tortor vel pellentesque malesuada, odio mi rhoncus nisi, non scelerisque leo orci at arcu. Nunc id sem id justo ullamcorper sodales. Aliquam vulputate libero faucibus lacus cursus a pulvinar est feugiat. Nam blandit neque vitae est sodales at sagittis nulla rhoncus. Duis fringilla mauris turpis, vel dignissim sapien. Curabitur placerat velit et nisi tincidunt in tristique urna iaculis. Quisque lacus nulla, iaculis vel lobortis vitae, varius ut justo. Suspendisse et dolor id massa dapibus ornare.
	</p>
	<br>
	<p>
		Morbi vitae elit neque. Phasellus diam diam, vestibulum at imperdiet vitae, sagittis a risus. In at erat erat. Sed velit nisi, scelerisque quis tristique vitae, bibendum eget massa. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In sodales consequat diam. Sed scelerisque, magna sit amet malesuada consequat, massa lacus sollicitudin nisi, quis pretium lorem sapien in mi.
	</p>
	<br>
	<p>
		Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam imperdiet eros eget nisl molestie pretium. Proin ut tortor sit amet lacus pulvinar hendrerit et nec sapien. Praesent eu odio nisl. Aenean iaculis volutpat adipiscing. Sed a tempus metus. Vestibulum gravida tempus imperdiet. Quisque quis pellentesque leo. Maecenas posuere nulla at eros vestibulum blandit. Vivamus nec metus at odio malesuada interdum ac in metus. Duis ultrices fringilla tortor eget rhoncus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse scelerisque nulla scelerisque sapien cursus nec rutrum lorem posuere. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean ante dolor, ultricies in bibendum sed, viverra quis tellus. Vivamus quis sapien sodales justo luctus lobortis vitae sit amet urna. Quisque sit amet lacinia lectus.</p>
	<br>
	<p>
		Proin eu nulla ac odio laoreet blandit. Duis tristique condimentum mauris, ac mollis metus dapibus sed. Phasellus congue, urna non sollicitudin consequat, lorem nibh dapibus mi, vitae dictum lectus urna id leo. Nam id dui lorem. Praesent eu ante at leo commodo varius. Curabitur nec turpis quis neque gravida iaculis eu eget est. Donec luctus tellus eu dolor imperdiet venenatis. Ut vitae nibh id sapien laoreet laoreet. Morbi tellus orci, rhoncus id elementum viverra, dignissim non orci. Pellentesque sed erat id urna luctus sodales. Nunc vel neque ac lectus vehicula hendrerit. Nunc egestas tristique euismod. Cras venenatis volutpat egestas. Aenean gravida ultricies ullamcorper. Morbi non porttitor lacus.
	</p>
	<br>
	<p>
		Praesent a nulla arcu. Etiam quis mauris id diam consectetur iaculis. Nam sed ligula metus. Integer est dui, sodales ac ultrices a, tincidunt sed neque. Aenean accumsan felis at dui eleifend eget molestie tellus venenatis. Maecenas ac tortor erat. Curabitur posuere neque id tellus lobortis interdum. Proin non orci quis nibh vestibulum malesuada. Suspendisse convallis tincidunt dictum. Nunc ut arcu eget mi placerat tempus quis quis turpis.
	</p>
	<br>
	<p>
		Aliquam ullamcorper, tortor vel pellentesque malesuada, odio mi rhoncus nisi, non scelerisque leo orci at arcu. Nunc id sem id justo ullamcorper sodales. Aliquam vulputate libero faucibus lacus cursus a pulvinar est feugiat. Nam blandit neque vitae est sodales at sagittis nulla rhoncus. Duis fringilla mauris turpis, vel dignissim sapien. Curabitur placerat velit et nisi tincidunt in tristique urna iaculis. Quisque lacus nulla, iaculis vel lobortis vitae, varius ut justo. Suspendisse et dolor id massa dapibus ornare.
	</p>
	<br>
	<p>
		Morbi vitae elit neque. Phasellus diam diam, vestibulum at imperdiet vitae, sagittis a risus. In at erat erat. Sed velit nisi, scelerisque quis tristique vitae, bibendum eget massa. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In sodales consequat diam. Sed scelerisque, magna sit amet malesuada consequat, massa lacus sollicitudin nisi, quis pretium lorem sapien in mi.
	</p>
</div>

app/views/home/user_prof.html.erb
<div class="user-profile">
	<div class="user-avatar">
		<a href="#" class="edit-avatar">Edytuj zdjęcie</a>
		<img src="http://25.media.tumblr.com/tumblr_m8fufgWFxN1rp2ebfo1_400.jpg" />
	</div>

	<div class="user-info">
		<a href="#" class="edit-box">Edytuj dane</a>
		<h1 class="your-name">Halina Goliatowska</h1>
		<p class="your-username">a.k.a GoHa</p><br>
		<p class="your-arrival">Dołączyła: 16 Lipiec 2012</p>
		Been there: <div class="been-there-bg">7889</div><div class="done-that-bg">12</div> :Done that
	</div>

	<div class="clear"></div>
</div>
<script>
	$('.user-avatar').hover(function(){
		$('.edit-avatar').delay(200).fadeIn('fast');
	},function(){
		$('.edit-avatar').delay(200).fadeOut('fast');
	});
	$('.user-info').hover(function(){
		$('.edit-box').delay(200).fadeIn('fast');
	},function(){
		$('.edit-box').delay(200).fadeOut('fast');
	});
</script>

app/views/home/user_reg.html.erb
user reg here