config/routes.rb
CcDev1::Application.routes.draw do

  match "/single_art" => "home#single_article", :as => :single_art
  match "/user_reg" => "home#user_reg", :as => :user_reg
  match "/user_prof" => "home#user_prof", :as => :user_prof
  match "/admin/example_form" => "mtest#example_form", :as => :example_form

  match "/admin" => "admin#index", :as => :admin
  match "/admin/login" => "admin#login", :as => :admin_login
  match "/admin/enter" => "admin#enter", :as => :admin_enter
  match "/admin/logout" => "admin#logout", :as => :admin_logout

  match "/szukaj/:keyword" => "home#search", :as => :search_word
  match "/szukaj" => "home#search", :as => :search

  devise_for  :users, 
              :path => 'uzytkownicy', 
              :path_names => { :sign_in => "logowanie", :sign_out => "wyloguj" }, 
              :controllers => { :registrations => "registrations" } do
  end

  resources :users, :path => 'users'
  resources :places
  resources :posts
  resources :preferences

  match "/nastepne-posty" => "home#load_more_posts", :as => :load_more_posts
  match "/post/:id" => "front_posts#show", :as => :single_post

  match "/miejsca" => "front_places#index", :as => :front_places
  match "/miejsca/:category" => "front_places#index"
  match "/miejsca/:category/strona_:page" => "front_places#index"
  match "/pokaz-miejsca" => "front_places#add_places_to_map", :as => :add_places_to_map
  match "/miejsce/:id" => "front_places#show", :as => :single_place  

  match "/kalendarz" => "home#calendar", :as => :calendar
  match "/kalendarz/:year/:month/:week" => "home#calendar", :as => :calendar_date
  match "/kontakt" => "home#contact", :as => :contact
  match "/o_nas" => "home#about", :as => :about
  match "/regulamin" => "home#terms", :as => :terms

  match "/:category" => "home#index", :as => :category

  root :to => 'home#index'

end

app/models/preference.rb
# -*- encoding: utf-8 -*-
class Preference < ActiveRecord::Base
  attr_protected :id

  mount_uploader :image, ImageUploader

  validates :name, :presence => true
  validates :image, :presence => true

  extend FriendlyId
  friendly_id :name, use: :slugged

  acts_as_taggable

  has_many :users_preferences
  has_many :users, :through => :users_preferences
end

app/controllers/preferences_controller.rb
# -*- encoding: utf-8 -*-
class PreferencesController < AdminController

  def index
    @preferences = Preference.order("id DESC").paginate(:page => params[:page], :per_page => 100)
  end


  def show
    @preference = Preference.find(params[:id])
  end


  def new
    @preference = Preference.new
    @available_tags = most_popular_tags(@preference.tags)
  end


  def edit
    @preference = Preference.find(params[:id])
    @available_tags = most_popular_tags(@preference.tags)
  end


  def create
    @preference = Preference.new(params[:preference])

    Rails.logger.info @preference.name

    @preference.tag_list = params[:p_tags].map{|k,v| v}.join(', ') if params[:p_tags].present?
    if @preference.save
      redirect_to preferences_url, notice: 'Artykuł utworzony.'
    else
      @available_tags = most_popular_tags(@preference.tags)
      render action: "new"
    end
  end


  def update
    @preference = Preference.find(params[:id])
    @preference.tag_list = params[:p_tags].map{|k,v| v}.join(', ') if params[:p_tags].present?    
    if @preference.update_attributes(params[:preference])
      redirect_to preferences_url, notice: 'Artykuł wyedytowany.'
    else
      @available_tags = most_popular_tags(@preference.tags)
      render action: "edit"
    end
  end


  def destroy
    @preference = Preference.find(params[:id])
    @preference.destroy

    redirect_to preferences_url
  end
end

app/views/preferences/_form.html.erb
<%= form_for(@preference) do |f| %>
  <% if @preference.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@preference.errors.count, "error") %> prohibited this preference from being saved:</h2>

      <ul>
        <% @preference.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit 'Zapisz', :class => "main-btn" %>
    <%= link_to 'Anuluj', preferences_path, :class => "cancel-btn" %>
  </div>

  <div class="field">
    <%= f.label :name, "Tytuł" %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= image_tag @preference.image.medium_fill.url if @preference.image.present? %><br/>
    <%= f.label :image, "Obraz" %>
    <%= f.file_field :image %>
    <%= f.hidden_field :image_cache %>
  </div>


  <div class=" field tag_module">
    <div class="field">
      <%= label_tag :tags_to_add, "Nowe tagi" %>
      <%= text_field :tags_to_add, '', :class => "new_tags" %>
      <%= link_to "Add new tags", "#", :onclick => "addNewTags(); return false;", :class => "aux-btn" %>
      <p>Tagi można oddzielać przecinkiem</p>
    </div>
    <table width="100%" cellspacing="0" cellpadding="0" class="no-styling-please">
      <tr>
        <td width="50%"> 
          <label>Tagi przypisane do tego wpisu</label><br>
          <div class="list_of_tags">
            <% last = 0 %>
            <% @preference.tag_list.each_with_index do |t, index| %>
              <span rel='<%= index %>' class='all_tags tagger tag_field' onclick='add_or_remove("<%= index %>");'>
                <span class="tag-tip"></span>
                <%= t %>
                <a href="" class="tag-x"></a>
                <input type='text' name='p_tags[<%= index %>]' value='<%= t %>' readonly='readonly' class='hide_tag'>
              </span>
            <% last = index %>
            <% end %>
          </div>
        </td>
        <td width="50%">
          <label>Najpopularniejsze tagi</label><br>
          <div class="available_tags">
            <% @available_tags.each_with_index do |t, index| %>
              <% a_index = last + index + 1 %>
                <span rel='<%= a_index %>' class='all_tags tagger available_tag' onclick='add_or_remove("<%= a_index %>");'>
                  <span class="tag-tip"></span>
                  <%= t.name %>
                  <a href="" class="tag-x"></a>
                  <input type='text' name='avail_p_tags[<%= a_index %>]' value='<%= t.name %>' readonly='readonly' class='hide_tag'>
                </span>
            <% end %>
          </div>
        </td>
      </tr>
    </table>
  </div>


  <script type="text/javascript">
    function addNewTags() {
      var last_index = 0;
      var tags_array = [];
      var old_tag_fields = $('.all_tags');    
      if (old_tag_fields.length > 0) {
        var indexes_array = [];
        old_tag_fields.each(function(){
            val = Number( $(this).attr('rel') );
            indexes_array.push(val);
        });
        var last_index = (Math.max.apply(Math, indexes_array))+1000;
      };
      var tags_string = $('.new_tags').val();
      if (tags_string.length > 0) {
        var tags_array = tags_string.split(", ");
        $.each(tags_array, function(index,value){
          var curr_index = parseInt(last_index) + index + 1;
          // console.log(curr_index+' - '+value);
          var already_present = $('input[value="'+value+'"]');
          if (already_present.length == 0) {
            var tid = curr_index;
            var new_tag_input = "<span rel='"+curr_index+"' class='all_tags tagger tag_field' onclick='add_or_remove(&#39;"+tid+"&#39;);'><span class='tag-tip'></span>"+value+"<a href='' class='tag-x'></a><input type='text' name='p_tags["+curr_index+"]' value='"+value+"' readonly='readonly' class='hide_tag'></span>"
            $('.list_of_tags').append(new_tag_input);
          } else {
            var first_present = $(already_present[0]).parent('span');
            if ( first_present.hasClass('tag_field') ) {
              alert('Tag "'+value+'" jest już przypisany do tego artykułu.');
            } else {
              add_or_remove( first_present.attr('rel') );
            };
          };
        });
        $('.new_tags').val('');
      };
    }
  </script>

  <script>
    function add_or_remove(tid) {  
      var this_obj = $('[rel="'+tid+'"]');
      if ( this_obj.hasClass('tag_field') ) {
        this_obj.removeClass('tag_field').addClass('available_tag');
        this_obj.children('input').attr('name', 'avail_p_tags['+tid+']');
        this_obj.appendTo('.available_tags');
      } else {
        this_obj.removeClass('available_tag').addClass('tag_field');
        this_obj.children('input').attr('name', 'p_tags['+tid+']');
        this_obj.appendTo('.list_of_tags');
      };
    };
  </script>

 
  <br><br>
  <div class="actions">
    <%= f.submit 'Zapisz', :class => "main-btn" %>
    <%= link_to 'Anuluj', preferences_path, :class => "cancel-btn" %>
  </div>
<% end %>

app/views/preferences/edit.html.erb
<h3>Edytuj wpis</h3>

<%= render 'form' %>

app/views/preferences/index.html.erb
<h3>
  Preferencje <%= link_to 'Nowy wpis', new_preference_path,:class => "mini main-btn" %>
</h3>

<%= will_paginate @preferences %>
<br>

<table>
  <tr>
    <th width='2%'>Id</th>
    <th>Zdjęcie</th>
    <th>Tytuł</th>
    <th>Utworzony</th>
    <th width='8%'>Opcje</th>
  </tr>
  <% @preferences.each do |preference| %>
    <tr>
      <td><%= preference.id %></td>
      <td><%= (image_tag preference.image.thumb.url) if preference.image.present? %></td>
      <td><%= preference.name %></td>
      <td><%= preference.created_at.strftime("%d.%m.%Y") %> - <%= preference.created_at.strftime("%H:%M") %></td>
      <td>
        <%= link_to '', edit_preference_path(preference), :class => "ico edit" %>
        <%= link_to '', preference, method: :delete, data: { confirm: 'Are you sure?' }, :class => "ico remove" %>
      </td>
    </tr>
  <% end %>
</table>

<br>
<%= will_paginate @preferences %>
<br>
<%= link_to 'Nowy wpis', new_preference_path,:class => "mini main-btn" %>

app/views/preferences/new.html.erb
<h3>Nowy wpis</h3>

<%= render 'form' %>

app/views/preferences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Description:</b>
  <%= @post.description %>
</p>

<p>
  <b>Start date:</b>
  <%= @post.start_date %>
</p>

<p>
  <b>Slug:</b>
  <%= @post.slug %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>