config/routes.rb
CcDev1::Application.routes.draw do

  match "/single_art" => "home#single_article", :as => :single_art
  match "/user_reg" => "home#user_reg", :as => :user_reg
  match "/user_prof" => "home#user_prof", :as => :user_prof
  match "/admin/example_form" => "mtest#example_form", :as => :example_form

  match "/admin" => "admin#index", :as => :admin
  match "/admin/login" => "admin#login", :as => :admin_login
  match "/admin/enter" => "admin#enter", :as => :admin_enter
  match "/admin/logout" => "admin#logout", :as => :admin_logout

  match "/szukaj/:keyword" => "home#search", :as => :search_word
  match "/szukaj" => "home#search", :as => :search

  devise_for  :users, 
              :path => 'uzytkownicy', 
              :path_names => { :sign_in => "logowanie", :sign_out => "wyloguj" }, 
              :controllers => { :registrations => "registrations" } do
  end

  resources :users, :path => 'users'
  resources :places
  resources :posts
  resources :preferences

  match "/nastepne-posty" => "home#load_more_posts", :as => :load_more_posts
  match "/post/:id" => "front_posts#show", :as => :single_post

  match "/miejsca" => "front_places#index", :as => :front_places
  match "/miejsca/:category" => "front_places#index"
  match "/miejsca/:category/strona_:page" => "front_places#index"
  match "/pokaz-miejsca" => "front_places#add_places_to_map", :as => :add_places_to_map
  match "/miejsce/:id" => "front_places#show", :as => :single_place  

  match "/kalendarz" => "home#calendar", :as => :calendar
  match "/kalendarz/:year/:month/:week" => "home#calendar", :as => :calendar_date
  match "/kontakt" => "home#contact", :as => :contact
  match "/o_nas" => "home#about", :as => :about
  match "/regulamin" => "home#terms", :as => :terms

  match "/:category" => "home#index", :as => :category

  root :to => 'home#index'

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Panel administracyjny CollegeCity</title>
  <%= stylesheet_link_tag "admin", :media => "all" %>
  <link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700,400italic,700italic|PT+Sans+Caption:400,700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'jquery.js', 'jquery_ujs.js', 'jquery-ui.js' %>
  <%= javascript_include_tag "ckeditor/init" %>
  <%= csrf_meta_tags %>

  <script type="text/javascript">
    function remove_fields(link) {
      $(link).prev("input[type=hidden]").val("1");
      $(link).closest(".field").hide();
    }

    function add_fields(link, association, content) {
      var new_id = new Date().getTime();
      var regexp = new RegExp("new_" + association, "g")
      $(link).parent().before(content.replace(regexp, new_id));
    }
  </script>

  <%= yield :javascript %>
</head>

<body>
  <% if alert.present? %>
  <div class="flash-error message" id="error"><%= alert %></div>
  <script type="text/javascript">
  $(document).ready(function() {
    $("div.flash-error").delay(5000).slideUp('medium');
  });
  </script>
  <% end %>
  <% if notice.present?  %>
  <div class="flash-notice message" id="notice"><%= notice %></div>
  <script type="text/javascript">
  $(document).ready(function() {
    $("div.flash-notice").delay(5000).slideUp('medium');
  });
  </script>
  <% end %>

  <div class="main-wrapper">
    <header><%= link_to image_tag('panel-logo.png'), admin_path %>
      <h1>Panel Administracyjny <%= link_to "Wróc do serwisu", root_url, :class => "return-to-site", :target => "_blank" %></h1>
    </header>

    <nav class="breadcrumbs">
      <div class="user-area" >
        <strong>Witaj!</strong> Admin
      </div>
      <span class="unstyled-nav">Na skróty:</span> 
      <%= link_to "Nowy artykuł", new_post_url %> 
      <%= link_to "Dodaj miejsce", new_place_url %> 
    </nav>
    <div class="admin-content">
      <aside class="main-nav">
        <ul>
          <li><%= link_to "Artykuły", posts_url %><span class="left-selected"></span></li>
          <li><%= link_to "Miejsca", places_url %> </li>
          <li><%= link_to "Użytkownicy", users_url %> </li>
          <li><%= link_to "Preferencje", preferences_url %> </li>
          <li><%= link_to "Wygląd", example_form_path %> </li>
          <li><%= link_to "Wyloguj", admin_logout_url %> </li>
        </ul>
      </aside>	

      <div class="page-content">
        <%= yield %>
      </div>
    </div>
    <div class="clear"></div>
  </div>
</body>
</html>

app/views/layouts/admin_login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Panel administracyjny CollegeCity</title>
    <%= stylesheet_link_tag "admin", :media => "all" %>
    <link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700,400italic,700italic|PT+Sans+Caption:400,700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <%= javascript_include_tag 'jquery.js', 'jquery_ujs.js', 'jquery-ui.js' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
      <% if alert.present? %>
        <div class="flash-error message" id="error"><%= alert %></div>
           <script type="text/javascript">
             $(document).ready(function() {
             $("div.flash-error").delay(5000).slideUp('medium');
              });
      </script>
    <% end %>
    <% if notice.present?  %>
      <div class="flash-notice message" id="notice"><%= notice %></div>
      <script type="text/javascript">
  $(document).ready(function() {
    $("div.flash-notice").delay(5000).slideUp('medium');
  });
      </script>
    <% end %>
    <div class="front-login-box">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>CollegeCity</title>
  <link rel="icon" type="image/png" href="http://collegecity.pl/assets/favi.png" />
  <link rel="apple-touch-icon" href="http://collegecity.pl/assets/apple-favi.png" />
  <meta property="og:type" content="website"/>
  <meta property="og:title" content="CollegeCity"/>
  <meta property="og:url" content="http://collegecity.pl"/>
  <meta property="og:image" content="http://collegecity.pl/assets/apple-favi.png"/>
  <meta property="og:description" content="CollegeCity - studencka platforma informacyjna. College lifestyle, fajni ludzie, życie nocne, student power, ciekawe miejsca. Pozytywna energia!"/>
  <link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700,400italic,700italic|PT+Sans+Caption:400,700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>

  <%= stylesheet_link_tag    'application'  %>
  <%= javascript_include_tag 'application'  %>
  
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false" %>
  <%= javascript_include_tag "http://google-maps-utility-library-v3.googlecode.com/svn/trunk/styledmarker/src/StyledMarker.js" %>  

  <% if Rails.env == 'production' %>
    <!-- Analytics code -->
    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-35205487-1']);
      _gaq.push(['_trackPageview']);
      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    </script>
  <% end %>
  
  <script>
    $(document).ready(function() {
      $(window).scroll(function() {
          if ($(this).scrollTop()> 68)
           {
           $('header').addClass('fix-me');
           $('#logo').removeClass("logo-cc");
           $('#logo').addClass("small-logo-cc");
           }
          else
           {
           $('header').removeClass('fix-me');
           $('#logo').removeClass("small-logo-cc");
           $('#logo').addClass("logo-cc");
           }
       });
      $(".close-me").click(function() {
        $('.top-notificator').hide();
      });
  });
  </script>

  <%= csrf_meta_tags %>
</head>
<body class="<%= params[:controller] %>-<%= params[:action] %>">
  <% if notice.present? %>
    <div class="top-notificator tm-notice">
      <p class="notice" style="display:none;"><%= notice %><span class="close-me">X</span></p>
    </div>  
    <script>
    $('.notice').delay(1000).slideDown("slow").delay(5000).slideUp("slow");
    </script>
  <% end %>
  <% if alert.present? %>
    <div class="top-notificator tm-error">
      <p class="alert"><%= alert %><span class="close-me">X</span></p>
    </div>
    <script>
    $('.alert').delay(1000).slideDown("slow").delay(5000).slideUp("slow");
    </script>
  <% end %>
  <div id="fb-root"></div>
  <script>
    (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1&appId=208374365888731";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
  </script>
  <div style="height: 109px;">
  <header>
    <div class="snooper">
      <div class="snoop-left"></div>
      <div class="snoop-mid">
          <% if user_signed_in? %>
            <%= link_to "Witaj, #{current_user.name_or_email}", edit_user_registration_path %> |
            <%= link_to "Wyloguj", destroy_user_session_path, :method => :delete %>
          <% else %>
            <%= link_to 'Zaloguj się', new_user_session_url %> |
            <%= link_to 'Zarejestruj się', new_user_registration_url %>
          <% end %>
          <%= form_tag search_url do %>
            <%= text_field_tag :keyword, "", :class => "main-search-area" %>
            <%= submit_tag "", :class => "search-btn" %>
          <% end %>          
      </div>
      <div class="snoop-right"></div>
    </div>
    <div class="navigation-area">
      <%= link_to "", root_url, :id => "logo", :class => "logo-cc" %>    
  		<nav>
        <a href="<%= category_url('rozrywka') %>" class="orange-bar">Rozrywka</a><span class="seperator"></span>
        <a href="<%= category_url('kultura') %>" class="green-bar">Kultura</a><span class="seperator"></span>
        <a href="<%= category_url('studia') %>" class="blue-bar">Studia</a><span class="seperator"></span>
        <a href="<%= category_url('lifestyle') %>" class="pink-bar">Lifestyle</a><span class="seperator"></span>
        <a href="<%= front_places_url %>" class="yellow-bar">Miejsca</a><span class="seperator"></span>
        <%= link_to "Kalendarz", calendar_path, :class => "white-bar" %>
  		</nav>
    </div>
    <div class="clear"></div>

  </header>
  </div>
  <div class="behind-bg">
    <div class="blurme"><div class="stripes"></div></div>
    <% if params[:controller] == 'front_posts' && params[:action] == 'show' %>
        <style>
            .behind-bg {
                background-image: url(<%= image_path @post.main_photo_link("main") %>);
                background-position: center center;
            }
        </style>
    <% end %>
  </div>
  
  <div class="glass-wrapper">
    <div class="main-content">
      <%= yield %>
    </div>
  </div>
  
    <% unless params[:controller] == 'home' && params[:action] == 'index' %>
      <%= render :partial => "shared/footer-link" %>
    <% end %>
    
  <div class="clearspace"></div>
</body>

app/views/layouts/map.html.erb
<!DOCTYPE html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>CollegeCity</title>
<link rel="icon" type="image/png" href="http://collegecity.pl/assets/favi.png" />
<link rel="apple-touch-icon" href="http://collegecity.pl/assets/apple-favi.png" />
  <meta property="og:type" content="website"/>
  <meta property="og:title" content="CollegeCity"/>
  <meta property="og:url" content="http://collegecity.pl"/>
  <meta property="og:image" content="http://collegecity.pl/assets/apple-favi.png"/>
  <meta property="og:description" content="CollegeCity - studencka platforma informacyjna. College lifestyle, fajni ludzie, życie nocne, student power, ciekawe miejsca. Pozytywna energia!"/>
  <link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700,400italic,700italic|PT+Sans+Caption:400,700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>

  <%= stylesheet_link_tag    'application'  %>
  <%= javascript_include_tag 'application'  %>

  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false" %>
  <%= javascript_include_tag "http://google-maps-utility-library-v3.googlecode.com/svn/trunk/styledmarker/src/StyledMarker.js" %>
  
  <% if Rails.env == 'production' %>
      <script type="text/javascript">
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-35205487-1']);
        _gaq.push(['_trackPageview']);
        (function() {
          var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
          ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
          var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();
      </script>
  <% end %>

  <%= csrf_meta_tags %>
</head>


<body class="<%= params[:controller] %>-<%= params[:action] %>">
  <% if notice.present? %>
    <div class="top-notificator tm-notice">
      <p class="notice" style="display:none;"><%= notice %></p>
    </div>  
    <script>
    $('.notice').delay(1000).slideDown("slow").delay(5000).slideUp("slow");
    </script>
  <% end %>
  <% if alert.present? %>
    <div class="top-notificator tm-error">
      <p class="alert"><%= alert %></p>
    </div>
    <script>
    $('.alert').delay(1000).slideDown("slow").delay(5000).slideUp("slow");
    </script>
  <% end %>
  <div id="fb-root"></div>
  <script>
    (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1&appId=208374365888731";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
  </script>
  <div style="height: 109px;">
      <header>
        <div class="snooper">
          <div class="snoop-left"></div>
          <div class="snoop-mid">
              <% if user_signed_in? %>
            <%= current_user.email %> | 
               <%= link_to "Wyloguj", destroy_user_session_path, :method => :delete %>
              <% else %>
                <%= link_to 'Zaloguj się', new_user_session_url %> |
                <%= link_to 'Zarejestruj się', new_user_registration_url %>
              <% end %>
          </div>
          <div class="snoop-right"></div>
        </div>
        <div class="navigation-area">
          <%= link_to "", root_url, :class => "logo-cc" %>    
      		<nav>
            <a href="<%= category_url('rozrywka') %>" class="orange-bar">Rozrywka</a><span class="seperator"></span>
            <a href="<%= category_url('kultura') %>" class="green-bar">Kultura</a><span class="seperator"></span>
            <a href="<%= category_url('studia') %>" class="blue-bar">Studia</a><span class="seperator"></span>
            <a href="<%= category_url('lifestyle') %>" class="pink-bar">Lifestyle</a><span class="seperator"></span>
            <a href="<%= front_places_url %>" class="yellow-bar">Miejsca</a><span class="seperator"></span>
            <%= link_to "Kalendarz", calendar_path, :class => "white-bar" %>
      		</nav>
        </div>
        <div class="clear"></div>
      </header>
  </div>

  <div class="map-content">
    <%= yield %>
  </div>  

  <div class="clearspace"></div>
</body>